random = 1

[in_batch]
seq_shuffling = 0
batch_shuffling = 0
shift_change = [0,0]

[in_train]
neg_seq = 0
pos_seq = 0
neg_batch = 0
pos_batch = 0
mix_ratio = [1,5]
shuffle_all_num = 500

[in_eval]
mix_ratio = [1,4]
shuffle_all_num = 100




