loss_type = "bce"
sub_loss = []

[weight_loss]
act = true
weight = [0.1, 0.9]


[bce]
alpha = 1.0
beta = 1.0
reduction = "mean"

[bpr]
margin = 1.0

[triplet]
margin = 1
neg_embs_sample = false

[triplet.use_neg_embs]
from_pos = 0
from_neg = 1
sample_num = 32


[cosine_triplet]
margin = 0.5
neg_embs_sample = false

[cosine_triplet.use_neg_embs]
from_pos = 0
from_neg = 1
sample_num = 100

[listwise_contrastive]
temperature = 0.1

[focal]
alpha = 0.25
gamma = 2.0

[infonce]
temperature = 0.2
sim = "cosine"

[inbatch_infonce_loss]
temperature = 1
sim = "cosine"
rowmask = true
neg_embs_sample = false 

[inbatch_infonce_loss.use_neg_embs]
from_pos = 0
from_neg = 1
sample_num = 500

[ado_infonce]
temperature = 0.07

