[model]




[model.emb]
id_emb = 128
feat_emb = 128
pos_emb = 128
dropout_rate = 0.2

[model.encoder]
maxlen = 101
hidden_units = 128
dropout_rate = 0.2
interval_k = 512


[model.encoder.id_encoder]
maxlen = 101
hidden_units = 128
diff = 128
num_experts = 1
num_blocks = 1
num_heads = 1
dropout_rate = 0.2
ffn_dropout_rate = 0.2
norm_first = true


[model.encoder.feat_encoder]
maxlen = 101
hidden_units = 128
diff = 128
num_experts = 1
num_blocks = 1
num_heads = 1
dropout_rate = 0.2
ffn_dropout_rate = 0.2
norm_first = true


[model.senet]
excitation_u = 16
excitation_i = 31

[model.fusion]
hidden_units = 128