loss_type = "bce"

sub_loss = ["cosine_triplet"]

batch_size = 128
num_epochs = 30
grad_clip_norm = -1.0
grad_accumulation_steps = 1
l2_emb = 0.0

[optimizer]
type = "Adam"
lr = 0.001
betas = [0.9, 0.98]
weight_decay = 0.0
eps = 1e-8

[scheduler]
type = "cosine_with_warmup_restarts"  
# type = 'constant'
warmup_steps = 2000
min_lr_ratio = 0.1
T_0 = 5000  
T_mult = 2   
eta_min_ratio = 0.05
restart_ratio = 0.1 


[logging]
log_grad_freq = 10
log_train_freq = 10
save_model_freq = 1  # 每多少个epoch保存一次模型

[model]
hidden_units = 32
num_blocks = 1
num_heads = 1
dropout_rate = 0.2
maxlen = 101
norm_first = false
dff = 32

[data]
num_workers = 0
shuffle_train = true
shuffle_valid = false

[eval]
acc_k = [1, 3]
distance = "dot"
